dataset: 'BRCA'
data_preprocessing: 
  filtering:
    mRNA: 
      variance: 0.1
      annova: 1000
    DNA:
      variance: 0.001
      annova: 1000
    miRNA:
      variance: 0
      annova: 502
  test_split: 0.3
  n_bins: 2
  min_rules: 1000
  fold_change: true
  discretize_level: 1 
  random_state: 41

compare_other: 
  filter: 0.3
  corr_threshold: 0.5
  epochs: 200
  hidden_units: 32
  learning_rate: 0.0001
  batch_size: 20
  drop_out: 0.05
  negative_corr: false
  pooling_ratio: 0.0
  ppi: true
  ppi_score: 500
  corr: false
  ppi_edge: 'score'
  discretized: true
  information: true
  n_bins: 3
  kegg: true
  kegg_filter: 0.05 
  kegg_topk: 50
  go: true
  go_filter: 0.05
  go_topk: 50
  select_k: 'auto'
  info_mean: true
  scale_edge: false
  decay: 0.001

biomarkers: 100

embedding_training: 
  learning_rate: 0.001
  output_channel: 128
  learning_epoch: 300

train_encoder: 
  learning_rate: 0.1 
  output_channel: 16
  learning_epoch: 300 
  print_interval: 1
  model: 'GAE' # support GAE and VGAE

arm_classification:
  topk: [ 1 , 5 , 10 , 20 , 30 , 40 , 50 , 100 , 150 , 200 , 500 , 1000 , 1500 , 2000  ]
  metric: 'interestingness_1' 
  data_path: './artifact/data_preprocessing'
  strategy: 'union' # support ['union', 'topk', 'difference']



knowledge_graph: 
  ppi_combined_score: 500
  ppi: true
  kegg_go: true
  synthetic: true
  corr: true
  edge_threshold: 0.2
  topk: 500
  discretized: true
  ppi_normalize: 'max_score' # support ['max' , 'binary' , "max_score"]
  kegg_normalize: 'max' # support ['max' , 'binary']
  kegg_sort: "PValue" # ["PValue","Fold Enrichment","Bonferroni","Benjamini","FDR"]
  kegg_topk: 500
  kegg_filter: 'synthetic' # support [ "syntheic" , "topk" ]
  ppi_filter: "synthetic" # support [ "syntheic" , null ]
  corr_filter: 0.9
  ac_normalize: "information" # support ['max' , 'binary' , 'information']'

model_training: 
  dataset: 'discretized_multiedges_multigraph' # support ['discretized_multiedges_multigraph', 'multiedges_multigraph', 'discretized_common_multigraph', 'unified' , 'correlation' , 'embedding' , 'unified_multigraph' , 'contrastive_multigraph' , 'triplet_multigraph' , 'triplet_multigraph' , 'binarylearning_multigraph' , 'common_multigraph]
  model: 'MultiGraphClassification' # support ['MultiGraphClassification' , 'BinaryLearning' , 'ContrastiveLearning' , 'TripletLearning']
  hidden_units: 32
  multihead: 1
  multihead_concat: false
  learning_rate: 0.0001
  learning_epoch: 200
  drop_out: 0.0
  batch_size: 10
  weight:  [ 5.96 , 14.97 , 1.83 , 5.73 , 21.93 ]
  enable_validation: true
  enable_testing: false
  enable_training: true
  alpha: 0.2
  binary: false
  optimizer: 'adam' # support ['adam' , 'sgd']
  decay: 0.0001
  gat_dropout: 0.0
  num_layer: 3
  num_block: 1
  pooling_rate: 0.5
  momentum: 0.1
  pooling: 'sag' # support ['sag' , 'topk']
