data_preprocessing: 
  mRNA: 
    variance: 0.1
    annova: 1000 
  DNA:
    variance: 0.001
    annova: 1000
  miRNA:
    variance: 0
    annova: 502

embedding_training: 
  learning_rate: 0.001
  output_channel: 128
  learning_epoch: 300

train_encoder: 
  learning_rate: 0.001 
  output_channel: 16 
  learning_epoch: 300 
  print_interval: 1
  model: 'GAE' # support GAE and VGAE
  
knowledge_graph: 
  ppi_combined_score: 300 
  
model_training: 
  dataset: 'unified_multigraph' # support ['unified' , 'correlation' , 'embedding' , 'unified_multigraph']
  model: 'MultiGraphClassification' # support ['MultiGraphClassification']
  hidden_units: 32
  learning_rate: 0.00001
  learning_epoch: 300
  drop_out: 0.1
  batch_size: 1
  weight: null # [ 5.96 , 14.97 , 1.83 , 5.73 , 21.93 ] 
  enable_validation: false
  enable_testing: true
  enable_training: true