data_preprocessing: 
  mRNA: 
    variance: 0.1
    annova: 1000 
  DNA:
    variance: 0.001
    annova: 1000
  miRNA:
    variance: 0
    annova: 502

embedding_training: 
  learning_rate: 0.001
  output_channel: 128
  learning_epoch: 300

train_encoder: 
  learning_rate: 0.001 
  output_channel: 16 
  learning_epoch: 300 
  print_interval: 1
  model: 'GAE' # support GAE and VGAE
  
knowledge_graph: 
  ppi_combined_score: 300 
  ppi: false
  kegg_go: false
  synthetic: true
  edge_threshold: 0.0
  
model_training: 
  dataset: 'triplet_multigraph' # support ['unified' , 'correlation' , 'embedding' , 'unified_multigraph' , 'contrastive_multigraph' , 'triplet_multigraph' , 'triplet_multigraph']
  model: 'TripletLearning' # support ['MultiGraphClassification' , 'BinaryLearning' , 'ContrastiveLearning' , 'TripletLearning']
  hidden_units: 32
  learning_rate: 0.0001
  learning_epoch: 600
  drop_out: 0.1
  batch_size: 5
  weight: null # [ 5.96 , 14.97 , 1.83 , 5.73 , 21.93 ] 
  enable_validation: true
  enable_testing: false
  enable_training: true
  alpha: 0.2
  binary: false