data_preprocessing: 
  mRNA: 
    variance: 0.1
    annova: 1000 
  DNA:
    variance: 0.001
    annova: 1000
  miRNA:
    variance: 0
    annova: 502

embedding_training: 
  learning_rate: 0.001
  output_channel: 128
  learning_epoch: 300

knowledge_graph: 
  ppi_combined_score: 300 
  
model_training: 
  dataset: 'unified' # support ['unified' , 'correlation' , 'embedding']
  model: 'MultiGraphClassification' # support ['MultiGraphClassification']
  hidden_units: 32
  learning_rate: 0.00001
  learning_epoch: 300
  drop_out: 0.1
  batch_size: 20
  weight: null # [ 5.96 , 14.97 , 1.83 , 5.73 , 21.93 ] 